name: Publish package to GitHub packages
on:
  release:
    types: [published]

jobs:
  publish:
    if: "!github.event.release.prerelease"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '16'
          distribution: 'temurin'
      - name: Publish package
        run: mvn --batch-mode deploy --file pom.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
